### ISSUE TITLE
Default extras

### ISSUE THREAD

**Issue by sbidoul** [sbidoul/pip-deepfreeze#83]
Developers typically need to remember to use `pip-df sync -x test,dev`. This is not optimal.

Two possibilities:
- sync install all extras by default
- configure default extras in `pyproject.toml`, in a `tool.pip-deepfreeze` section.

**Comment by rousseldenis** [comment]
> Developers typically need to remember to use `pip-df sync -x test,dev`. This is not optimal.
> 
> Two possibilities:
> 
> * sync install all extras by default
> * configure default extras in `pyproject.toml`, in a `tool.pip-deepfreeze` section.

I would say a section for pip deepfreeze could be the best way as pip will just look at normal section by default, but when you are in developement (and run pip-deepfreeze), you normally have all extras installed.
